# Generated by Django 4.1.7 on 2023-04-03 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('Deptno', models.IntegerField(primary_key=True, serialize=False)),
                ('Dloc', models.CharField(max_length=100, unique=True)),
                ('Deptname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('Empid', models.IntegerField(primary_key=True, serialize=False)),
                ('Ename', models.CharField(max_length=100, unique=True)),
                ('Esal', models.IntegerField()),
                ('Hiredate', models.DateField(unique=True)),
                ('Deptno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
    ]
